export type UltronStatus='IDLE'|'LISTENING'|'THINKING'|'RESPONDING'|'EXECUTING'|'WARNING'|'ERROR';
export type UltronMood='CALM'|'FOCUSED'|'AMUSED'|'CONFIDENT'|'SUSPICIOUS'|'WARNING'|'CRITICAL';
export interface DecisionPipeline{guardian:{status:'STANDBY'|'SCANNING'|'CLEAR'|'ALERT';riskScore:number;message:string};critic:{status:'STANDBY'|'ANALYZING'|'APPROVED'|'REJECTED';intent:string;confidence:number};executor:{status:'STANDBY'|'EXECUTING'|'COMPLETED'|'HALTED'|'ERROR';tool?:string|null;output?:any;executionTime?:string};}
export interface DecisionRecord{id:string;timestamp:string;promptSummary:string;intent:string;guardianStatus:'CLEAR'|'ALERT'|'SCANNING'|'STANDBY';criticStatus:'APPROVED'|'REJECTED'|'ANALYZING'|'STANDBY';executorStatus:'COMPLETED'|'EXECUTING'|'HALTED'|'STANDBY'|'ERROR';riskScore:number;confidence:number;toolUsed?:string|null;rationale?:string;model?:string;}
export interface NetworkNode{id:string;label:string;emoji:string;type:'network'|'ai'|'memory'|'system'|'io'|'security';status:'ONLINE'|'ACTIVE'|'CONNECTED'|'STANDBY'|'BUSY'|'ALERT'|'DISCONNECTED'|'OFFLINE';latency:string;description:string;category:string;angle:number;distance:number;}
export interface ChatMessage{id:string;sender:'USER'|'ULTRON'|'SYSTEM';text:string;timestamp:string;mood?:UltronMood;toolUsed?:string|null;model?:string|null;pipeline?:DecisionPipeline;telemetry?:{responseTime?:string;tokens?:number;engine?:string};}
export interface PersonalityConfig{ULTRON_NAME:string;ULTRON_ROLE:string;ULTRON_PERSONALITY:string;ULTRON_INSTRUCTIONS:string;}
export interface SystemDiagnostics{ultronState:string;version:string;coreTemperature:string;neuralLoad:string;memoryHeapUsed:string;uptimeSeconds:number;guardianStatus:string;activeNodes:any[];live?:any;}
export interface UserDirectiveItem{id:string;label:string;prompt:string;}
export interface UserMemoryDirectives{userRequirements:string;customDirectives:UserDirectiveItem[];}
