import React, { useEffect, useRef } from 'react';
import { useUltron } from '../core/ultronContext';
import { MOOD_COLORS } from './UltronCore';
import { hexToRgba } from '../utils/colorLerp';

type Particle={x:number;y:number;vx:number;vy:number;life:number;maxLife:number;size:number;kind:0|1|2;char:string};
const CHARS=['0','1','A','F','X','7','E','9','C','3'];
export const DataTraceEmitter:React.FC<{width?:number;height?:number}> = ({width=520,height=520}) => {
  const {status,mood}=useUltron(); const canvasRef=useRef<HTMLCanvasElement|null>(null); const statusRef=useRef(status); statusRef.current=status; const colorRef=useRef(MOOD_COLORS[mood]||MOOD_COLORS.CALM); colorRef.current=MOOD_COLORS[mood]||MOOD_COLORS.CALM;
  useEffect(()=>{ const canvas=canvasRef.current; const ctx=canvas?.getContext('2d',{alpha:true}); if(!canvas||!ctx)return; const dpr=Math.min(window.devicePixelRatio||1,1.25); canvas.width=Math.floor(width*dpr); canvas.height=Math.floor(height*dpr); canvas.style.width=`${width}px`; canvas.style.height=`${height}px`; ctx.setTransform(dpr,0,0,dpr,0,0); const cx=width/2,cy=height/2,core=145; const particles:Particle[]=[]; let raf=0,last=0,lastEmit=0;
    const spawn=(now:number)=>{ const angle=Math.random()*Math.PI*2,radius=core*(.88+Math.random()*.12),s=statusRef.current,speed=s==='THINKING'?2.6+Math.random()*1.8:s==='EXECUTING'?2.2+Math.random()*1.4:1.1+Math.random()*.7; particles.push({x:cx+Math.cos(angle)*radius,y:cy+Math.sin(angle)*radius,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:0,maxLife:36+Math.random()*28,size:1+Math.random()*1.8,kind:Math.random()>.72?1:Math.random()>.45?0:2,char:CHARS[(Math.random()*CHARS.length)|0]}); if(particles.length>75)particles.splice(0,particles.length-75); lastEmit=now; };
    const frame=(now:number)=>{ const dt=Math.min(32,now-(last||now)); last=now; ctx.clearRect(0,0,width,height); const s=statusRef.current,c=hexToRgba((colorRef.current as any).primary),active=s==='THINKING'||s==='EXECUTING',interval=s==='ERROR'||s==='WARNING'?24:active?36:s==='RESPONDING'?52:95; if(now-lastEmit>=interval){spawn(now);if(active&&Math.random()>.45)spawn(now);} for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life+=dt/16.67;p.x+=p.vx*dt/16.67;p.y+=p.vy*dt/16.67;const a=Math.max(0,1-p.life/p.maxLife);if(p.life>=p.maxLife){particles.splice(i,1);continue;}ctx.globalAlpha=a*.85;if(p.kind===0){ctx.strokeStyle=`rgba(${c.r},${c.g},${c.b},${a})`;ctx.lineWidth=p.size;ctx.beginPath();ctx.moveTo(p.x-p.vx*3,p.y-p.vy*3);ctx.lineTo(p.x,p.y);ctx.stroke();}else if(p.kind===1){ctx.fillStyle=`rgba(${c.r},${c.g},${c.b},${a*.8})`;ctx.font=`${8+p.size*1.5}px monospace`;ctx.fillText(p.char,p.x,p.y);}else{ctx.fillStyle=`rgba(255,255,255,${a})`;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();}}ctx.globalAlpha=1;raf=requestAnimationFrame(frame);}; raf=requestAnimationFrame(frame); return()=>cancelAnimationFrame(raf); },[width,height]);
  return <canvas ref={canvasRef} className="absolute inset-0 pointer-events-none z-15 ultron-heavy-effect" aria-hidden="true"/>;
};
