import React,{useEffect} from 'react';
import {useUltron} from './ultronContext';
import * as api from '../services/ultronApi';
const map:Record<string,string>={internet:'internet',github:'github',memory:'supabase_memory',omniroute:'ai_brain',instagram:'quantum_matrix',administrator:'guardian'};
const good=(s:string)=>/^(CONNECTED|ONLINE|ELEVATED|LOCAL_READY|LOCAL_READY_SUPABASE_CONFIGURED)$/.test(s);
const VALID=['CALM','FOCUSED','AMUSED','CONFIDENT','SUSPICIOUS','WARNING','CRITICAL'];
export const RuntimeBridge:React.FC=()=>{const{nodes,toggleNodeStatus,setStatus,mood}=useUltron();
 useEffect(()=>{window.dispatchEvent(new CustomEvent('ultron:mood',{detail:mood}));},[mood]);
 useEffect(()=>{let dead=false;const sync=async()=>{try{const d:any=await api.fetchSystemStatus();const s=d.live?.status||d.status||{};setStatus(s.omniroute?.status==='OFFLINE'?'WARNING':'IDLE');window.dispatchEvent(new CustomEvent('ultron:live-status',{detail:d.live||d}));for(const[source,id]of Object.entries(map)){if(dead)break;const live=s[source]?.status,node=nodes.find(n=>n.id===id);if(!live||!node||node.status==='ACTIVE')continue;if(good(node.status)!==good(String(live)))toggleNodeStatus(id);}}catch{/* Core may be offline. */}};
 const click=(e:Event)=>{const b=(e.target as HTMLElement|null)?.closest('button');const host=b?.parentElement;const mesh=host?.querySelector('[id^="mesh-node-"]');if(mesh){e.preventDefault();e.stopImmediatePropagation();sync();}};
 document.addEventListener('click',click,true);sync();const t=window.setInterval(sync,5000);return()=>{dead=true;clearInterval(t);document.removeEventListener('click',click,true);};},[nodes,setStatus,toggleNodeStatus]);return null;};
